# Generated by Django 4.2.4 on 2023-08-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
