# Generated by Django 4.2.4 on 2023-08-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=400)),
                ('projects', models.ManyToManyField(to='api.project')),
                ('skills', models.ManyToManyField(to='api.skill')),
            ],
        ),
    ]
