# Generated by Django 4.2.4 on 2023-08-17 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_education'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectrating',
            unique_together={('user', 'project')},
        ),
        migrations.AlterIndexTogether(
            name='projectrating',
            index_together={('user', 'project')},
        ),
    ]
